function GT_MessageAlert(GT_AnalysisInfo, guiParams)
    
if guiParams.saveStructToggle == true
    try
        if length(GT_AnalysisInfo.(guiParams.scoringID).data.fileIDs) >= 1
            structSaved = 'yes';
        end
    catch
        structSaved = 'yes, but it is empty [  ]';
    end
else
    structSaved = 'no';
end

if guiParams.saveFigsToggle == true
    try
        if length(GT_AnalysisInfo.(guiParams.scoringID).data.fileIDs) >= 1
            figsSaved = num2str(length(unique(GT_AnalysisInfo.(guiParams.scoringID).data.fileIDs)));
        end
    catch
        figsSaved = '0';
    end
else
    figsSaved = 'none';
end

if isempty(GT_AnalysisInfo.(guiParams.scoringID).data)
    msg = msgbox({'Sleep Scoring Analysis Results:', ...
        ' ', ...
        ['Parameters ID: ' guiParams.scoringID], ...
        ' ',...
        ' - No sleep data was found.', ...
        ' ', ...
        [' - Results saved: ' structSaved], ...
        ' ', ...
        [' - Summary figures: ' figsSaved],...
        ' '}, 'Analysis Complete', 'warn');
    waitfor(msg)
else
    sleepTime = 0;
    numberOfTrials = length(unique(GT_AnalysisInfo.(guiParams.scoringID).data.fileIDs));
    for f = 1:length(GT_AnalysisInfo.(guiParams.scoringID).data.binTimes)
        sleepTime = sleepTime + length(GT_AnalysisInfo.(guiParams.scoringID).data.binTimes{f,1});
    end
    sleepTime_min = (sleepTime*5)/60;   
    
    msg = msgbox({'Sleep Scoring Analysis Results:', ...
        ' ', ...
        ['Parameters ID: ' guiParams.scoringID], ...
        ' ', ...
        [' - ' num2str(sleepTime_min) ' minutes of sleep data was found.']...
        ' ' ...
        [' - ' num2str(numberOfTrials) ' unique trials.']...
        ' ', ...
        [' - ' num2str(length(GT_AnalysisInfo.(guiParams.scoringID).data.fileIDs)) ' unique events.']...
        ' ', ...
        [' - Results saved: ' structSaved], ...;
        ' ', ...
        [' - Summary figures saved: ' figsSaved]...
        ' '}, 'Analysis Complete', 'help');
    waitfor(msg)
end

end